# Generated by Django 3.0.7 on 2020-06-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerdesh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
