# Generated by Django 3.0.7 on 2020-06-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerdesh', '0002_auto_20200613_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='pub_date'),
        ),
    ]
